docs/SUMMARY.md
docs/demos/usb-camera-demo-rpi4.md

Add the USB camera demo on Raspberry Pis to the demos in `SUMMARY.md`, so it is displayed on GitBooks.

Link in Raspberry Pi USB Camera Demo

---

docs/README.md
docs/demos/usb-camera-demo.md

The home page does not properly link to sections. This fixes that.

Fix broken links

---

docs/community/contributing.md
docs/demos/opc-thermometer-demo.md
docs/development/development.md

Fixes links in developer guide and re-formats OPC UA demo

Fix documentation links

---

docs/demos/opc-thermometer-demo.md
docs/demos/usb-camera-demo-rpi4.md
docs/demos/usb-camera-demo.md
docs/development/broker-development.md
docs/development/debugging.md
docs/development/development-walkthrough.md
docs/development/development.md
docs/development/handler-development.md
docs/discovery-handlers/onvif.md
docs/discovery-handlers/opc-ua.md
docs/discovery-handlers/udev.md

Fix linking to crictl instructions and development TOC

Fix linking to crictl instructions and development TOC

---

docs/development/development-walkthrough.md

Finally rebased the http-extensibility branch in Akri: https://github.com/project-akri/akri/pull/413
This updates the example to match updated dependencies in template and http-extensibility branch

Update extensibility with newer dependencies changes

---

docs/demos/opc-thermometer-demo.md
docs/demos/usb-camera-demo-rpi4.md
docs/demos/usb-camera-demo.md
docs/development/broker-development.md
docs/discovery-handlers/onvif.md
docs/discovery-handlers/opc-ua.md
docs/discovery-handlers/udev.md
docs/user-guide/monitoring-with-prometheus.md

Now that a release has been made in `project-akri`, we can pull `latest` containers from `ghcr.io/project-akri`

Replace final references of Deis Labs

---

docs/user-guide/cluster-setup.md

fixes https://github.com/project-akri/akri/issues/352 by installing latest but linking to release notes which specifies versions that have been checked

install latest k8s versions and point to release notes

---

docs/README.md

Add statement of CNCF hosting to site base

Add statement of CNCF hosting to site base

---

docs/development/debugging.md
docs/discovery-handlers/onvif.md
docs/discovery-handlers/opc-ua.md
docs/discovery-handlers/udev.md
docs/user-guide/customizing-an-akri-installation.md
docs/user-guide/getting-started.md

Documentation for changes in https://github.com/project-akri/akri/pull/437

Documentation on Deploying Jobs with Akri

---

docs/demos/opc-thermometer-demo.md

As explained in this issue https://github.com/project-akri/akri/issues/464 the OPC UA demo is out of date. 
The demo uses the [.NET Standard library](https://github.com/OPCFoundation/UA-.NETStandard) for building demo servers however it does not tie to a specific tag of the branch, so the line numbers the demo references are out of date. This ties the demo to the appropriate tag and simplifies some of the demo flow.
fixes https://github.com/project-akri/akri/issues/464

Fix OPC-UA demo to specific tag

---

docs/demos/usb-camera-demo-rpi4.md

I added a note to step 9 as missing this caused an afternoon of searching for resolutions

Raspberry PI Camera Demo - Added Note to Step 9

---

docs/development/development.md

1. how to create crd before running locally
2. mention creating UDS directory before running agent locally

preparation work in running locally chapter

---

docs/user-guide/cluster-setup.md

This PR accompanies https://github.com/project-akri/akri/pull/508

Update docs for using containerd as default container runtime socket

---

docs/community/contributing.md

This PR accompanies changes made by https://github.com/project-akri/akri/pull/510

Update contribution guidelines for the new version workflow

---

docs/demos/opc-thermometer-demo.md

Fixed from previous [PR](https://github.com/project-akri/akri-docs/pull/55).

Updated OPC UA Demo

---

docs/development/development.md

Updating doc to reflect changes to rust v1.68.1 from this PR https://github.com/project-akri/akri/pull/574

Update Rust Version to 1.68.1

---

docs/development/broker-development.md

update doc to address change in https://github.com/project-akri/akri/pull/561
closes #66

Update broker properties documentation with instance hash suffix

---

CODEOWNERS

Forgot to do this change in this repository, so here it is.

Add @diconico07 to CODEOWNERS

---

docs/development/broker-development.md

Update Onvif discovery handler document to reflect the ONVIF_DEVICE_UUID property introduced in the PR:
https://github.com/project-akri/akri/pull/630

add description of ONVIF_DEVICE_UUID exposed by Onvif DH

---

docs/development/test-cases-workflow.md

This is the documentation part of project-akri/akri#623

Documentation for revamp of e2e test framework

---

docs/discovery-handlers/onvif.md

Add uuid filter document
Add document of secret data schema used by Onvif Discovery Handler
Add document of secret data schema used by Onvif sample broker

Add document of uuid filter and schema for secret data for Onvif Discovery Handler

---

docs/architecture/agent-in-depth.md
docs/discovery-handlers/onvif.md

Add document of discoveryProperties in Agent

Add discoverProperties document

---

docs/community/contributing.md

This pull request pertains to issue #82(Community -> Contributing -> CLA section is outdated)

CLA Section replaced with DCO description

---

docs/SUMMARY.md
docs/demos/onvif-authentication-access.md

Add a document to demonstrate passing credentials to Onvif DH to discover authentication-enabled Onvif cameras.
Part of #87

add document to demo Onvif DH authentication access

---

docs/user-guide/monitoring-with-prometheus.md

documents two new metrics from Agent

add new metrics from Agent

---

README.md
docs/README.md

Add LF trademark statement

---

docs/README.md
docs/SUMMARY.md
docs/demos/video-links.md

Would like to suggest we include the links of several key introduction videos in the documentation.

New page under demo for links of introduction and demo videos.

---

docs/user-guide/customizing-an-akri-installation.md

Update of Configuration result in a different behavior since the agent's refactor in order to prevent deletion of existing Instances on Configuration update.
Agent's now only looks for updates to the capacity and broker properties.
All other modifications currently requires user to delete then re-apply the Configuration.

Update doc to take into account the new Configuration update behavior
