docs/SUMMARY.md, docs/development/building.md, docs/development/development.md
Akri's [developer document](https://github.com/deislabs/akri/blob/v0.6.5/docs/development.md) was accidentally not moved over to this new documentation repository. This brings it over and clarifies that the building document is for simplifying building Akri's containers.
=> Add in Developer Guide

docs/development/development.md
Increase development Rust version to be `1.54.0` to match updates made in https://github.com/deislabs/akri/pull/361.
Also, fixes broken links in development document.
=> Increase rust version and fix broken links

docs/demos/opc-thermometer-demo.md, docs/demos/usb-camera-demo-rpi4.md, docs/demos/usb-camera-demo.md, docs/development/broker-development.md, docs/development/building.md, docs/development/debugging.md, docs/development/development-walkthrough.md, docs/development/development.md, docs/development/handler-development.md, docs/discovery-handlers/onvif.md, docs/discovery-handlers/opc-ua.md, docs/discovery-handlers/udev.md, docs/user-guide/cluster-setup.md, docs/user-guide/customizing-an-akri-installation.md, docs/user-guide/getting-started.md, docs/user-guide/monitoring-with-prometheus.md, docs/user-guide/requesting-akri-resources.md
This separates out instructions on storing `crictl` configuration Helm values in a `AKRI_HELM_CRICTL_CONFIGURATION` variable out from the rest of the cluster setup steps. The instructions are referenced at the top of every section that contains installations. It also adds the `AKRI_HELM_CRICTL_CONFIGURATION` variable to all installations.
This will reduce the amount of slot reconciliation errors people encounter.
Fixes deislabs/akri#97
=> Separate out crictl configuration instructions

docs/community/contributing.md, docs/demos/opc-thermometer-demo.md, docs/development/development.md, docs/development/test-cases-workflow.md
This aims to improve the flow of the developer guide by making clearer what dependencies and steps are needed to develop each part of Akri. It makes the document focused on Akri's Rust components. Previously, it mentioned installing and building the ONVIF .NET broker but not the OPC UA .NET broker nor the python applications. To avoid this inconsistency and also bulking up the documentation site with development instructions for Akri's samples, it points to the non-Rust component READMEs in Akri core which this PR adds https://github.com/deislabs/akri/pull/389.
=> Improve development documentation

docs/community/contributing.md, docs/development/development.md
- Updates installation docs to reflect Akri's current Rust version `v1.55.0`
- Instructs to update version with `./version.sh` instead of `version.sh`
=> Use proper Rust version and prefix script runs with `./`

docs/community/contributing.md
This change is associated with the PR in Akri main: https://github.com/project-akri/akri/pull/426.
Instead of running workflows based on the flags in PR titles, we made changes so that workflow runs are now triggered by PR labels. This change is to update the contributing docs and add details about the PR labels.
=> Update contributing doc to add details about PR labels

docs/user-guide/cluster-setup.md
Associated documentation for https://github.com/project-akri/akri/pull/427.
=> Choosing K8s Distribution to set Container Runtime Socket Path for `crictl`

docs/development/broker-development.md, docs/development/development.md, docs/user-guide/customizing-an-akri-installation.md, docs/user-guide/getting-started.md
In preparation of Akri's next release, this points to the new Rust version and the production Helm charts.
=> Update docs with latest rust version and to point to prod Helm Chart

docs/demos/usb-camera-demo.md
Closes #26 by mentioning extra modules may be needed for cloud VMs such as in the case of Azure.
=> Add note about additional kernel modules for cloud vms

docs/demos/usb-camera-demo-rpi4.md, docs/demos/usb-camera-demo.md, docs/discovery-handlers/udev.md
For some udev devices, it is necessary for the discovery handler to have mounted access to the `/run/udev` directory. Before Akri version `v0.6.5` this was done by default. This PR adds documentation to mount it with Helm if issues occur. An investigation should be done as to whether it should be set as a default in the Helm chart again. Issue to follow: https://github.com/project-akri/akri/issues/476
=> Recommend mounting udev `/run/udev` directory

docs/demos/usb-camera-demo-rpi4.md, docs/demos/usb-camera-demo.md, docs/development/broker-development.md, docs/user-guide/customizing-an-akri-installation.md, docs/user-guide/getting-started.md, docs/user-guide/monitoring-with-prometheus.md
Some usb cameras use multiple kernel nodes, one for capture and others for metadata. This fixes the issue of discovering these extra metadata nodes as unique cameras (project-akri/akri#438) by modifying the udev rule to only discover cameras with capture capabilities.
=> Ensure only USB cameras with capture capabilities are discovered in udev examples

CODEOWNERS
This ensures that maintainers are tagged as reviewers in PR by default
=> Add CODEOWNERS file for Akri Docs

docs/demos/usb-camera-demo-rpi4.md, docs/demos/usb-camera-demo.md, docs/discovery-handlers/udev.md
Removes recommendation to mount `/run/udev` directory as it is now mounted by default (https://github.com/project-akri/akri/pull/487).
This reverts commit bf3b8308c99fdbba457e04bc8bba776b00466a85 (https://github.com/project-akri/akri-docs/pull/37), reversing
changes made to fb62edaa4f6fcf2e98fb99d40bc1d934819918dd.
=> Remove recommedation to mount `/run/udev` directory

docs/development/development.md
Akri uses Rust 1.61.0. Update docs to appropriately reflect this.
Signed-off-by: Kate Goldenring <kagold@microsoft.com>
=> Update Rust version

docs/demos/usb-camera-demo-rpi4.md, docs/demos/usb-camera-demo.md
Little nit to make sure udev rule is properly evaluated in demo.
Signed-off-by: Kate Goldenring <kate.goldenring@fermyon.com>
=> Remove extra escape character in usb camera demo udev rule

docs/development/development.md
This PR removes dockershim references + updates them with the containerd paths and changes to use rust 1.63 instead of 1.61.
=> Update documentation for rust 1.63 toolchain + containerd

docs/demos/opc-thermometer-demo.md
caught this small mistake just now, needed to correct the portnum on the second OPC PLC container deployment for it to work properly.
=> nit: corrected portnum on OPC containers

docs/discovery-handlers/udev.md
This commit adds a section in the udev device handler documentation, it explains how to use the `groupRecursive` option and what are the effects of doing so.
It is the documentation linked to project-akri/akri#564
=> udev: Add documentation of `groupRecursive` option

proposals/onvif-discovery-handler-secret-info-schema.md
Propose a schema of secret information in discoveryProperties passed to Onvif DiscoveryHandler
related to https://github.com/project-akri/akri/issues/250
=> proposal for onvif secret data schema

docs/development/development-walkthrough.md, docs/development/development.md
- updated cargo version in the toolchain install instruction to version 1.70 as it is required by cargo-generate which is used to create a discovery-handler project from a template
- added "html" package import to the Go module for the http server because it is required as dependency in the build step (docker build)
=> Added missing dependency and updated cargo version

docs/development/building.md, docs/development/development.md, docs/development/test-cases-workflow.md
This adapts the development sections of the documentation after the revamp of the build system in akri repository
=> Adapt documentation to take new build system into account

docs/community/contributing.md, docs/community/roadmap.md
Adding the adopter section and instruction for adopters to add themselves.
Also fixing a broken link:
> **Roadmap**
> Akri uses a [single project board](https://github.com/project-akri/akri/projects/1) to track issues.
=> Adding adopter section and link to adopters.md.

docs/discovery-handlers/udev.md
added device mount permissions section for corresponding PR https://github.com/project-akri/akri/pull/737
=> added device mount permissions section
